language: generic
dist: xenial

before_install:
  - sudo apt-get update -qq

before_script:
  - sudo apt-get install -y dos2unix
  - dos2unix bootstrap.sh
  - bash bootstrap.sh
  - dos2unix bootstrap_webdev.sh
  - bash bootstrap_webdev.sh

script:
  - pytest ./experiment_provisioner/test/test.py -s
  - cd docs; make html

after_script:
  - cd ..; python openbenchmark.py --action=terminate
